import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Bowlby_One} from "next/font/google";

import { Bowlby_One_SC } from "next/font/google";


import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bowlbyOne = Bowlby_One_SC({
  variable: "--font-bowlby-one",
  subsets: ["latin"],
  weight: "400", // Especifique o peso se necessário
});


export const metadata: Metadata = {
  title: "Burguer Haven",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bowlbyOne.variable} antialiased bg-[#1E1E1E] font-bowlby-one`}
      >
        {children}
      </body>
    </html>
  );
}
